### ISSUE TITLE
Excluding the '#recycle' directory from s3cmd upload

### ISSUE THREAD

**Issue by brunobhr** [s3tools/s3cmd#1039]
I'm using s3cmd on a Synology NAS.

I built an exclusion file and the --exclude-from=/path/to/exc/file option but it doesn't work.

I already tried this:

"#recycle/*" 
"*/#recycle/*"
"/volume1/JOB/#recycle/*"
"*/JOB/#recycle/*" 
"/JOB/#recycle/*" 
"/volume1/JOB/#recycle" 
"#recycle/"  

but s3cmd still tries to upload the '#recycle' folder contents.

Any ideas?

**Comment by fviard** [comment]
Sadly it is not documented and not very explicit because of implementation reasons, but for your case, you can use one of the following things methods:
> with --exclude-from
> [#]recycle

or 

> with --rexclude-from
> \#recycle

(in both cases with eliminate lines starting with #, but in the first case we use "globbing" and so [#] will work with it and path the filter. And in the second case, we use regexp, so you can use \# or [#])
