### ISSUE TITLE
Still uploads if access denied?

### ISSUE THREAD

**Issue by dm17** [s3tools/s3cmd#1064]
So I had a variable in the URL which failed to get set in a backup script... So I accidentally uploaded data to a bucket that isn't mine! I can't tell exactly what happened. It spent time uploading, but then it said failed. So where did the file go?

```
upload: '/tmp/tmpfile-YtibQ0l6px5UkjuIVW2e' -> 's3://database/database-local-2020-01-01T1106.tar.gz'  [1 of 1]
 613131 of 613131   100% in    0s  1779.04 kB/s  done
upload: '/tmp/tmpfile-YtibQ0l6px5UkjuIVW2e' -> 's3://database/database-local-2020-01-01T1106.tar.gz'  [1 of 1]
 613131 of 613131   100% in    0s  1877.15 kB/s  done
ERROR: S3 error: 404 (NoSuchBucket): The specified bucket does not exist
ERROR: S3 error: 403 (AccessDenied): Access Denied
```

Thanks!

**Comment by fviard** [comment]
Hi,
Maybe the bucket is setup in write-only mode.
You can try to upload a dummy file to the same bucket to see what will
happen.

Florent

**Comment by dm17** [comment]
I confirmed with AWS that it did not upload... s3cmd is weird that it does upload somewhere before getting access denied; I guess I'll never know.

**Comment by fviard** [comment]
if you did a put command (upload), this is logic, even if confusing.
Unlike for the "sync", where there is a round trip of commands with the server, in the case of the upload, we just send the file directly to the cloud, to be more efficient in most cases.
But, because of how is designed the protocol, you send the whole request (that includes all the data), before the server will accept or refuse it.
It's a http request, "all or nothing" kind.
This is why, in your case, everything is sent, (that is the server that received all the data), before it tells us that he can't accept it because the bucket does not exist or you don't have the right acl for it.

So, nothing to be afraid of, except the lost upload time.
