### ISSUE TITLE
Upload files failed - raspberry pi ceph cluster

### ISSUE THREAD

**Issue by Ei3rb0mb3r** [s3tools/s3cmd#1069]
I have the following problem:

s3cmd --configure could establish a successful connection

cephuser@admin:~/s3cmd-2.0.2 $ ./s3cmd mb s3://TESTBUCKET
Bucket 's3://TESTBUCKET/' created

cephuser@admin:~/s3cmd-2.0.2 $ ./s3cmd ls
2020-01-26 23:14  s3://NEWBUCKET
2020-01-27 00:06  s3://TESTBUCKET

After the successful creation of a bucket the following error occurs:

```
cephuser@admin:~/s3cmd-2.0.2 $ ./s3cmd ls
2020-01-15 21:35  s3://ossperf-testbucket
2020-01-15 21:35  s3://testbucket
cephuser@admin:~/s3cmd-2.0.2 $ s3cmd put text.txt s3://testbucket
upload: 'text.txt' -> 's3://testbucket/text.txt'  [1 of 1]
 0 of 0     0% in    0s     0.00 B/s  failed
WARNING: Upload failed: /text.txt (No status line received - the server has closed the connection)
```

Log: ceph-rgw-gateway-node1.log

```
   -30> 2020-01-27 00:39:26.913766 4d377610  2 req 1:0.027470:s3:PUT /NEWBUCKET/setup.py:put_obj:recalculating target
   -29> 2020-01-27 00:39:26.913795 4d377610  2 req 1:0.027499:s3:PUT /NEWBUCKET/setup.py:put_obj:reading permissions
   -28> 2020-01-27 00:39:26.913816 4d377610  2 req 1:0.027519:s3:PUT /NEWBUCKET/setup.py:put_obj:init op
   -27> 2020-01-27 00:39:26.913838 4d377610  2 req 1:0.027543:s3:PUT /NEWBUCKET/setup.py:put_obj:verifying op mask
   -26> 2020-01-27 00:39:26.913857 4d377610  2 req 1:0.027562:s3:PUT /NEWBUCKET/setup.py:put_obj:verifying op permissions
   -25> 2020-01-27 00:39:26.913883 4d377610  5 Searching permissions for identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=test, acct_name=test, subuser=, perm_mask=15, is_admin=0) mask=50
   -24> 2020-01-27 00:39:26.913920 4d377610  5 Searching permissions for uid=test
   -23> 2020-01-27 00:39:26.913929 4d377610  5 Found permission: 15
   -22> 2020-01-27 00:39:26.913942 4d377610  5 Searching permissions for group=1 mask=50
   -21> 2020-01-27 00:39:26.913954 4d377610  5 Permissions for group not found
   -20> 2020-01-27 00:39:26.913962 4d377610  5 Searching permissions for group=2 mask=50
   -19> 2020-01-27 00:39:26.913976 4d377610  5 Permissions for group not found
   -18> 2020-01-27 00:39:26.913984 4d377610  5 -- Getting permissions done for identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=test, acct_name=test, subuser=, perm_mask=15, is_admin=0), owner=test, perm=2
   -17> 2020-01-27 00:39:26.914007 4d377610  2 req 1:0.027712:s3:PUT /NEWBUCKET/setup.py:put_obj:verifying op params
   -16> 2020-01-27 00:39:26.914033 4d377610  2 req 1:0.027737:s3:PUT /NEWBUCKET/setup.py:put_obj:pre-executing
   -15> 2020-01-27 00:39:26.914052 4d377610  2 req 1:0.027757:s3:PUT /NEWBUCKET/setup.py:put_obj:executing
   -14> 2020-01-27 00:39:26.914563 4d377610  1 -- 192.168.178.50:0/3901186134 --> 192.168.178.50:6800/1073 -- osd_op(unknown.0.0:523 3.4
```

**Comment by fviard** [comment]
You should check your s3cfg configuration regarding the host_base and host_bucket settings.
What is happening is that when you create or list buckets, you are using the base url (host_base).
But when you try to manipulate something inside a bucket, you are using the host_bucket url.

And an amazon s3, normally, you are using "dns-based" paths for bucket.
for example, your test.py object in s3://TESTBUCKET will be operated with a path like that:
```
TESTBUCKET.s3.mydomain.com/test.py
```
(so TESTBUCKET being inside the domain name).

In your case, if it is a custom setup of a s3 server, probably you have not the "dns-based" path that are supported, but just the "virtual-path-based" path.
So, the path should be like:
```
s3.mydomain.com/TESTBUCKET/test.py
```

Your host bucket, should probably changed to something like:  
`"s3.mydomain.com"`  (without the %(bucket)s)

Otherwise, s3cmd is probably targetting TESTBUCKET.s3.mydomain.com that does not exist or accept connection, and so you have the error.

(Similar issue could happen if you try to use HTTPS and the server does not support it, or the opposite)
