### ISSUE TITLE
Option to disable setuid/setguid behavior

### ISSUE THREAD

**Issue by socketwench** [s3tools/s3cmd#1085]
I'm having a problem with s3cmd in my backup container. The container is configured to run as a non-privileged user. This is fine on the initial sync to persistent storage, but subsequent syncs tend to fail with an unknown OS error:

`"ERROR: Download of 'xmlsitemap/NXhscRe0440PFpI5dSznEVgmauL25KojD7u4e9aZwOM/1.xml' failed (Reason: Unknown OsError 0)",
        "ERROR: Exiting now because of fatal error",
        "",
        "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
        "    An unexpected error has occurred.",
        "  Please try reproducing the error using",
        "  the latest s3cmd code from the git master",
        "  branch found at:",
        "    https://github.com/s3tools/s3cmd",
        "  and have a look at the known issues list:",
        "    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions",
        "  If the error persists, please report the",
        "  following lines (removing any private",
        "  info as necessary) to:",
        "   s3tools-bugs@lists.sourceforge.net",
        "",
        "",
        "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
        "",

The command works as expected when *not* using a persistent directory and forcing s3cmd to download everything each time. 

I suspect the problem is that s3cmd is setting the setuid/setguid bit and trying to run as root. Is there a way to disable this behavior? 
`

**Comment by fviard** [comment]
Hi,
I'm not quite sure of what is going on with your docker storage.
But, for the question about s3cmd settings,
you can use the following option "**--no-preserve**" to tell s3cmd to not try to restore fs attributes.
(So, with that option, s3cmd will download the file, but not try to set its mode, ownership and timestamp).

If ever you still try to investigate the root cause, don't hesitate to post updates here.
Something that can help you are the flags "-v -d" of s3cmd that will give you debug output.
