### ISSUE TITLE
SSL certificate verification failure

### ISSUE THREAD

**Issue by r-chris** [s3tools/s3cmd#1130]
I recently setup a `minIO` **gateway** to an Azure Blob storage backend. `minIO` runs inside a k8s cluster, which uses `nginx-ingress` to setup (let's encrypt) certificates and application url routing. I can access the `minIO` page through `https://` without issues.

I have configured access for `s3cmd` which initially seemed to work well and is able to show me all the available buckets, when using: `s3cmd -c ~/.s3/s3cfg ls s3://`

Unfortunately, when trying to call `s3cmd -c ~/.s3/s3cfg ls s3://my-awesome-bucket/` I receive the following error:
```
ERROR: SSL certificate verification failure: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
```

I have also tried running that same command with the `--no-ssl` and `--no-check-certificate` options, but I only get this output then:

```
ERROR: Error parsing xml: syntax error: line 1, column 0
ERROR: b'default backend - 404'
ERROR: S3 error: 404 (Not Found)
```

In contrast, I was able to use `boto3` as well as `rclone` successfully to create new objects in `my-awesome-bucket`, so I assume there may be another issue related to `s3cmd` here?

I am using `s3cmd version 2.1.0` (installed through `brew install s3cmd`) on macOS Catalina (10.15.6).

**Comment by fviard** [comment]
I would suggest to have a look at the following settings in your s3cfg config:
host_base
host_bucket

Do they have the same value?

To understand, there are 2 ways to access a bucket with s3, by path or by dns.
if your domain is like mydomain.com,
when you do a non specific bucket operation, like list, it will use host_base, so for example:
- FROM mydomain.com GET /

When you do an operation targeting a specific bucket, it is host_bucket that is used.
And depending of what you set inside, dns or path style access will be used.

For example, if you want to list files inside the bucket "hello" and your host_bucket value is:
- dns style used:
host_bucket = %(bucket)s.s3.amazonaws.com
FROM hello.s3.amazonaws.com GET /
- path style used:
host_bucket = s3.amazonaws.com
FROM s3.amazonaws.com GET /hello/

The consequence is that, if you use dns style, you should have a cname (or a *) in your ssl certificate for the domain name associated with your bucket. Otherwise, you should ensure to not have "%(bucket)s" in your host_bucket, and so path style will be used. (But not all services support that).

So, at first, i will recommend you to check that you have the same thing in host_base and host_bucket, to use path style access.

**Comment by r-chris** [comment]
Ok thanks - that was very helpful. I had indeed configured the s3cfg according to the "dns style" (which worked for another provider I was using until now), but it looks like `minIO` supports the "path style" here.

**Comment by vadorvatsal** [comment]
What has to be done to resolve this ?
