### ISSUE TITLE
Does s3cmd trust Amazon Trust Services?

### ISSUE THREAD

**Issue by TadaakiKutsuna** [s3tools/s3cmd#1134]
Does s3cmd trust Amazon Trust Services?

I'm currently using s3cmd on AWS S3 in ap-northeast-1 region.
The other day I received the following email from AWS.

Email body from AWS
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
Hello,

In 2018, AWS announced a broad migration of AWS services’ SSL/TLS certificates to our own Certificate Authority, Amazon Trust Services. Consistent with this change, and beginning March 2021, Amazon S3 and Amazon CloudFront will begin migrating the Certificate Authority for each services’ default certificate. Using our own Certificate Authority, AWS services can better manage the security practices used to handle our default certificates.

Your action may be required to ensure your applications continue normal operation after this change. If you already use other AWS services, your application most likely already trusts Amazon Trust Services as many AWS services have already migrated. Visit https://www.amazontrust.com/repository/ for more information about Amazon Trust Services. 
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

I would like to know if s3cmd will not cause any problems when switching to Amazon Trust Services.
Do I need to upgrade them to the latest version?

**Comment by fviard** [comment]
By default, s3cmd is using the ssl/tls root certificates that are provided by your system.
So, if their certificate authority is included in certificates embedded by os distribution or trusted by any common root authority, then you should not expect any problem.
Otherwise, you would have to install their root certificate in your system, but I don't think that it will be the case.

You can easily check if your system has any issue with a "amazon migrated service" by seing if you can do a "curl" request to any of their migrated service for example.

**Comment by stuaxo** [comment]
I've only really used ec2 and s3 a bit, what is their migrated service ?
