### ISSUE TITLE
WARNING: Unable to remote copy files

### ISSUE THREAD

**Issue by nshah14285** [s3tools/s3cmd#1156]
Hello,

Using 
OS: Ubuntu 20.04
S3cmd: 2.0.2

I have created two files 1.js and 2.js with same content. After that I tried to sync files using below command from terminal
`/usr/bin/s3cmd -v sync --delete-removed /home/test/cdn/ s3://test/`

**Output**

> INFO: No cache file found, creating it.
INFO: Compiling list of local files...
INFO: Running stat() and reading/calculating MD5 values on 9 files, this may take some time...
INFO: Retrieving list of remote files for s3://test/ ...
INFO: Forwarding request to us
INFO: Found 9 local files, 7 remote files
INFO: Verifying attributes...
INFO: Summary: 1 local files to upload, **1 files to remote copy**, 0 remote files to delete
upload: '/home/test/cdn/1.js' -> 's3://test/1.js'  [1 of 1]
 7 of 7   100% in    0s    26.37 B/s  done
**WARNING: Unable to remote copy files** 's3://test/1.js' -> 's3://test/2.js'
upload: '/home/test/cdn/2.js' -> 's3://test/2.js'  [2 of 2]
 7 of 7   100% in    0s    29.12 B/s  done
Done. Uploaded 14 bytes in 1.0 seconds, 14.00 B/s.

Don't understand why it throws this warning `**WARNING: Unable to remote copy files** 's3://test/1.js' -> 's3://test/2.js'`
Also, why it consider `**1 files to remote copy**` where both 1.js and 2.js files are created in the local folder.

When I created another two files 3.js and 4.js with different content then it does not throw any warning.

**Output**

> INFO: No cache file found, creating it.
INFO: Compiling list of local files...
INFO: Running stat() and reading/calculating MD5 values on 11 files, this may take some time...
INFO: Retrieving list of remote files for s3://test/ ...
INFO: Forwarding request to us
INFO: Found 11 local files, 9 remote files
INFO: Verifying attributes...
INFO: Summary: 2 local files to upload, **0 files to remote copy**, 0 remote files to delete
upload: '/home/test/cdn/3.js' -> 's3://test/3.js'  [1 of 2]
 12 of 12   100% in    0s    48.34 B/s  done
upload: '/home/test/cdn/4.js' -> 's3://test/4.js'  [2 of 2]
 12 of 12   100% in    0s    48.90 B/s  done
Done. Uploaded 24 bytes in 1.0 seconds, 24.00 B/s.

How to fix this? Is this a known bug?

Thanks,
Nishit Shah

**Comment by fviard** [comment]
HI,
s3cmd sync is smart, and so, in order to be more efficient, if it detects
files that have the exact same content, it will upload the first one and
then just do a remote copy instead of uploading again the content to create
the second file.

In your case, for some reason it does not work, but you don't have to worry
because it is just a warning. If the remote copy fails, we still upload the
file the old way.

That being said, it could be interesting to know why your remote copy
failed.
Are you using aws or a custom s3 service? You can run the command with the
-d flag to have more details.

Le mar. 24 nov. 2020 à 16:19, nshah14285 <notifications@github.com> a
écrit :

**Comment by nshah14285** [comment]
@fviard 

Thanks for your super quick response.
Yes, I observe that it tries to copy files remotely.
It solves the warning after I gave ACL permission to the S3 bucket user.

**s3cmd is really very smart.**

Thank You,
Nishit Shah
