### ISSUE TITLE
Correct order of options

### ISSUE THREAD

**Issue by FFKL** [s3tools/s3cmd#1159]
Hello! I've created a [zsh plugin](https://github.com/FFKL/s3cmd-zsh-plugin) for s3cmd. And I want to understand the correct order of options :smile:. Help command shows this pattern:
```
Usage: s3cmd [options] COMMAND [parameters]
```
But there is a lot of options for exact commands:
```
--limit=NUM           Limit number of objects returned in the response body (only for [ls] and [la] commands)
```
It works correctly for all of these examlpes:
```
s3cmd ls --limit=1 s3://bucket
s3cmd --limit=1 ls s3://bucket
s3cmd ls s3://bucket --limit=1
```
I want to limit usage of options by concrete command. Can I do it? Will it work for all commands correctly?

**Comment by fviard** [comment]
Nice to know that you are working on zsh auto-completion, this would be a very useful feature.

As of today, the config parser consideres all the arguments as globals.
Even if some of them are command specifics or useless for some commands.
Because of that, as you have noticed, you can put the arguments in the order that you want and it would be ok in all cases.
So far, it is somehow a feature.

So if you want to limit by command on the zsh plugin side, that should be ok for s3cmd that you provide the arguments in the order that fits better with your plugin.

**Comment by FFKL** [comment]
@fviard thank you! And another question. s3cmd supports only slash as delimeter in prefix?
https://github.com/s3tools/s3cmd/blob/55597d16937085be3fc8894f23d958241a9aad9f/S3/S3.py#L398-L402

**Comment by FFKL** [comment]
@fviard I think, I figured it out. This question is irrelevant :smile:
