### ISSUE TITLE
Stop support Python 2

### ISSUE THREAD

**Issue by pinkavaj** [s3tools/s3cmd#1170]
The goal of this issue is to gather informatins whatever it is possible to abandon Python 2 support.

Python 2 is not officialy supported any more, this project aims to be compatible with Python 3, which is now probably the dominant Python version. Keeping Python 2 compatibility adds a bit of extra effort to keep the legacy code running.

So is the Python 3 only the relevant version (:thumbsup:) or is Python 2 still needed (:-1: )

**Comment by fviard** [comment]
So far, it is a feature to keep python2 support in order to still be able to run on old devices.
As far as I know, there should not be prejudice to still have python2 retro compatibility, except the burden on the maintainers?
We will probably drop the support for python2 when it will be quite deprecated.

Closing as no action to be done.
