### ISSUE TITLE
2.1.0-r1 is broken. Module Import Error

### ISSUE THREAD

**Issue by AdamVB** [s3tools/s3cmd#1181]
Using alpine:latest

```
$ s3cmd put --acl-public ./machine-user/crl/crl.pem  s3://machine-user-crl
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
Error loading some components of s3cmd (Import Error)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Invoked as: /usr/bin/s3cmd put --acl-public ./machine-user/crl/crl.pem s3://machine-user-crl
Problem: <class 'ModuleNotFoundError: No module named 'S3'
S3cmd:   unknown version. Module import problem?
python:   3.8.8 (default, Mar 15 2021, 13:10:14) 
[GCC 10.2.1 20201203]
environment LANG=None
Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3099, in <module>
    from S3.ExitCodes import *
ModuleNotFoundError: No module named 'S3'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by alpersid** [comment]
I have the same issue using the last version of alpine.

**Comment by alpersid** [comment]
Seems that the issue was solved by updating python3 to latest version (3.9.4-r0):

$ cat /etc/alpine-release
3.13.4
$ apk add --upgrade python3
(1/14) Upgrading musl (1.2.2-r0 -> 1.2.2-r2)
(2/14) Upgrading expat (2.2.10-r1 -> 2.3.0-r0)
(3/14) Upgrading ncurses-terminfo-base (6.2_p20210109-r0 -> 6.2_p20210403-r0)
(4/14) Upgrading ncurses-libs (6.2_p20210109-r0 -> 6.2_p20210403-r0)
(5/14) Installing libbz2 (1.0.8-r1)
(6/14) Installing libffi (3.3-r2)
(7/14) Installing gdbm (1.19-r0)
(8/14) Installing xz-libs (5.2.5-r0)
(9/14) Installing libgcc (10.2.1_git20210328-r0)
(10/14) Installing libstdc++ (10.2.1_git20210328-r0)
(11/14) Installing mpdecimal (2.5.1-r1)
(12/14) Installing readline (8.1.0-r0)
(13/14) Installing sqlite-libs (3.35.4-r0)
**(14/14) Installing python3 (3.9.4-r0)**
Executing busybox-1.32.1-r5.trigger
$ apk search -v s3cmd --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
s3cmd-doc-2.1.0-r1 - Command line tool for managing Amazon S3 and CloudFront services (documentation)
s3cmd-2.1.0-r1 - Command line tool for managing Amazon S3 and CloudFront services
$ apk add  s3cmd --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
(1/5) Installing py3-six (1.15.0-r1)
(2/5) Installing py3-dateutil (2.8.1-r3)
(3/5) Installing libmagic (5.40-r0)
(4/5) Installing py3-magic (0.4.20-r1)
(5/5) Installing s3cmd (2.1.0-r1)
Executing busybox-1.33.0-r5.trigger
OK: 83 MiB in 46 packages

$ s3cmd --recursive put version s3://$s3bucket/$BU/$environment/configurations/
upload: 'version' -> 's3://infra-deployment-dm/DEV/PROD/configurations/version'  [1 of 1]
 41 of 41   100% in    0s   880.96 B/s  done

**Comment by point212** [comment]
If someone has problems with 'just' upgrading python3 (like me was), you could use this command. 

`apk add --upgrade --allow-untrusted \
            --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main \
            --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing  \
            --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
            python3 py3-dateutil=2.8.1-r3 s3cmd`

It is work well for me.

**Comment by sfgeorge** [comment]
Thank you @point212 👏   Note that the above fix worked for me on alpine:3.13 (not alpine:3.12).

**Comment by denists1984** [comment]
Not sure if it will help to everyone. Recently got the same problem as mentioned above. I found this similar issue:
https://github.com/s3tools/s3cmd/issues/1057

And by just coping S3 directory from python3.9 to python 3.8 solved the problem:

```
RUN apk add --no-cache s3cmd --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ && \
    cp -r /usr/lib/python3.9/site-packages/S3 /usr/lib/python3.8/site-packages/ 
```

My setup:
/ # s3cmd --version
s3cmd version 2.1.0
/ # cat /etc/alpine-release
3.13.3

**Comment by fviard** [comment]
Should now be fixed with master and new versions.
