### ISSUE TITLE
Exit code 0 on failure

### ISSUE THREAD

**Issue by bazzilic** [s3tools/s3cmd#1190]
In certain scenarios, error state produces an exit code 0, which makes it hard to write scripts with proper error handling.
In particular, if access to the destination path is denied, s3cmd would fail with exit code 0:

```
C:\Users\bazzilic> wsl s3cmd get s3://XXX/abc.plt /d/abc/abc.plt
ERROR: Skipping /d/abc/abc.plt: Permission denied

C:\Users\bazzilic> $LASTEXITCODE
0
```

This is not a WSL quirk, in other instances there is a proper exit code on error:

```
C:\Users\bazzilic> wsl s3cmd asdflkj asdlkfjh
ERROR: Invalid command: asdflkj

C:\Users\bazzilic> $LASTEXITCODE
64
```

Version of s3cmd:

```
C:\Users\bazzilic> wsl s3cmd --version
s3cmd version 2.0.2
```

**Comment by fviard** [comment]
Thank you very much for your report.

One purpose of s3cmd is to be easily scriptable, and so this is the purpose of the exit code.
It looks like that the "get" command that was not properly returning the right exit code, and it now fixed in master.

Don't hesite to open another issue if you also encounter such a case with another command.
Thanks
