### ISSUE TITLE
host_base host used for canonical request calculation used with extra path

### ISSUE THREAD

**Issue by crwnl3ss** [s3tools/s3cmd#1196]
Hello! 
Using s3cmd we encountered strange behavior using our own s3 storage.
config example:
```
host_base = 127.0.0.1:8000/api/v2/s3/
```
At the stage of generating the signature, we get the following beginning of the canonical request:
`b'GET\n/\n\nhost:127.0.0.1:8000/api/v2/s3/\nx-amz-content-sha256:e3b0c44298fc`
e.g. path of the endpoint url used as host neither canonical_uri:
https://github.com/s3tools/s3cmd/blob/ee4b303d814d35230ee51d5b04ef51d302d35506/S3/Crypto.py#L237
For example aws golang sdk used another approach, splitting url into host and uri:
https://github.com/aws/aws-sdk-go/blob/be8c07dcb635ca6c3f567d4173e95dad09a3efe5/aws/signer/v4/v4.go#L643
Is this behavior correct or is it some kind of bug?

**Comment by fviard** [comment]
Hi,
sorry for the long reply.

I think that our behavior is correct, because the concept is that the path that is inside the "host_base" is not really part of the "path" of the resource within the s3 namespace.
But I could be wrong.
In my opinion, the way aws sdk does is that they don't consider this case as there is no "host base subfolder" concept with aws, but they used to have the "bucket name" either in the domain name, or in the direct subpath.
