### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by valentina-paniza** [s3tools/s3cmd#1239]
I'm trying to set a new policy to my bucket and I'm using [this](https://www.linode.com/community/questions/19796/public-read-access-for-object-storage-bucket) as reference.
The thing is I'm not sure where 's3cmd' is running. I found it on many folders related to homebrew, and tried placing the JSON file there, but it is still not working. I also tried puting the JSON on the same folder as the .s3cmd config file, but fails. 

Thank you in advanced!

**Comment by bes1002t** [comment]
Not sure what this ticket is about. Do you want to execute "s3cmd" tool and you don't know whether the tool is installed on your client? If you are using linux, you can check out this command "which s3cmd".

**Comment by fviard** [comment]
If I understand well, you see the following command in the Linode documentation:
`s3cmd setpolicy bucket_policy_example.json s3://example_bucket`

And you are wondering where s3cmd is installed, so that you can put the bucket_policy_example.json file in the right folder so that it will be found?

For this argument of the command, you don't necessarily put just the name of the file, but a filepath, so the place where s3cmd is installed is irrelevant.

For example, you can put your `bucket_policy_example.json` in the current folder you are in your console when you call s3cmd, and it should work.
Otherwise, you can put a full path to where you want the file to be located, like `/home/myname/myfolder/mysubfolder/bucket_policy_example.json`.
