### ISSUE TITLE
 POST or PUSH operations from s3cmd fail on a certain internet connection

### ISSUE THREAD

**Issue by seaders** [s3tools/s3cmd#148]
Currently automating a build script to push resources to our s3 bucket. Nothing too complicated, and I had done most of the testing out of office, but as soon as I got into there, the whole thing started to fall apart, and I'm crazy confused why.

A simple command like (with both 'mybucket' existing on s3 and 'file.ext' existing in the directory I'm running the command from),

s3cmd put file.ext s3://mybucket/

was failing with either

[Errno 104] Connection reset by peer

or

[Errno 32] Broken pipe

I know there's an issue with s3 with files over 5GB of size, but these files are nowhere near that, they're less than 1MB, never mind more than 1GB. The really weird thing was that another program, http://www.bucketexplorer.com/ worked perfectly, doing the exact same operations, on the same network.

What was weirder still was to test everything out, I tethered my laptop to my phone's 3G connection, and straight away everything worked perfectly again, and when I got home, and tested the commands again there, it worked perfectly again.

Any idea as to what might be causing this error on our work network, with s3cmd, but not Bucket Explorer?

**Comment by fviard** [comment]
This issue should now be fixed in master.
Please give it a try.

**Comment by RichardJECooke** [comment]
I had this issue too with a 2MB database backup file from Cape Town to Ireland.
Using the latest code in the master branch fixed it today.

**Please will you (repository owners) publish this fix to the Sourceforge release (https://sourceforge.net/projects/s3tools/files/s3cmd), or if you no longer maintain that, then close the Sourceforge page.**  

Otherwise it's confusing for people who download the 'latest' release from a year ago and encounter bugs. Our team spent a day trying to investigate what could be going wrong with our cron and network settings before we found this issue.

**Comment by kac-** [comment]
`([Errno 104] Connection reset by peer)` on Ireland.
US - no problem.
4 years, no solution, cheers.

**Comment by fviard** [comment]
@kac- it is not because you have a similar error message that it is the same issue.

Did you try to use the latest MASTER version?
Can you try to give use a debug log (run the command with "-d") for your case that has the issue (ireland?).
