### ISSUE TITLE
incorporate multi-threaded gets/puts from s4cmd

### ISSUE THREAD

**Issue by nchammas** [s3tools/s3cmd#356]
I recently heard about [s4cmd](https://github.com/bloomreach/s4cmd) and have been using it mainly to upload files at a quicker rate to S3.

Have the maintainers of s3cmd considered incorporating some of the substantial performance improvements in s4cmd back here? The most interesting one seems to be multi-threaded gets/puts.

**Comment by nobodyman** [comment]
@mdomsch Thanks for your explanation.   In your opinion would it be easier to implement features that allow s3cmd to work alongside existing tools such as <a href="http://www.gnu.org/software/parallel/">gnu-parallel</a>?   For example,  let's pretend we had this functionality:

*  initiate multipart upload but don't actually send anything e.g. `s3cmd put bigfile.zip  s3://mybucket/bigfile.zip --begin-multipart`
* upload a single part of a multipart upload  `e.g. s3cmd put bigfile.zip s3://mybucket/bigfile.zip --multipart-id=12345`

With this functionality (along with `listmp`, which already exists) you would have everything you need to write a script that you could pass gnu-parallel (or xargs, etc).  Instead of one process and multiple threads you'd essentially fork multiple processes, each uploading a portion of the multi-part upload. 

Too kludgey?

**Comment by fviard** [comment]
@nobodyman I think that you can upload in parallel multiple files BUT that it is NOT possible to upload in parallel one multi part file, because parts should be uploaded one after the other.

**Comment by nobodyman** [comment]
If I'm reading the API docs correctly, I thing you can do concurrent multipart uploads on the same object id: http://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html#distributedmpupload

**Comment by fviard** [comment]
@nobodyman : I can be wrong, but I don't think that your understanding of this doc is right. In my opinion, what they want to say is that you can start multiple multipart uploads of the same file in the same time, the last one being the one that overwrite the others each time. But not that you can upload parts in parallel.
So it is like you try to upload 3 times the file in parallel, but each one sending parts in sequence.

**Comment by nobodyman** [comment]
Certainly possible I'm reading it wrong as I'm not very familiar w/ the spec yet, but I see at least one other project that ostensibly implements this parallel multipart upload feature (e.g. <a href="https://github.com/mumrah/s3-multipart">s3-multipart</a>).  Thing is, they aren't as feature-rich or as well-tested as s3cmd.

**Comment by fviard** [comment]
Even if we can't implement it now, that is an interesting question.
https://aws.amazon.com/fr/blogs/aws/amazon-s3-multipart-upload/
Its old, but let suppose that it is possible yes.
If you have time, is it possible to give a try to s3-multipart to see if it still works?

**Comment by nobodyman** [comment]
Thanks for finding that link, helps clear things up for me.   Also I'd be happy to give s3-multipart a try and let you know how it goes.

**Comment by nchammas** [comment]
Closing this feature request since it's a big ask with no practical path forward.
