### ISSUE TITLE
Issue with get requests from Frankfurt zone

### ISSUE THREAD

**Issue by MrCheck** [s3tools/s3cmd#481]
I'm using the latest version (1.5.2) which supports buckets located in frankfurt. Listening and uploading of files work fine, but when I try to download a file I get the following error:

>s3cmd get s3://[BUCKET]/test.txt --force
>s3://[BUCKET]/test.txt -> ./test.txt  [1 of 1]
>s3://[BUCKET]/test.txt -> ./test.txt  [1 of 1]
>ERROR: S3 error: Unknown error

Downloading files from other regions like Ireland or US works fine. Is there any known issue with downloading files from Frankfurt?

Thanks a lot in advance!

**Comment by mdomsch** [comment]
No known failures. What does --debug show?

**Comment by MrCheck** [comment]
Thanks for your quick response. Here's the output:

<code>
DEBUG: signature-v4 headers: {'x-amz-content-sha256': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': 'AWS4-HMAC-SHA256 Credential=[ACCESSKEY]/20150216/EU/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=99ab040842ac06dd10f35815a1e5b29e06bb1990a60e6d0c41b96a627c504bab', 'x-amz-date': '20150216T134031Z'}
s3://[BUCKET]/test_1gb.bin -> ./test_1gb.bin  [1 of 1]
DEBUG: get_hostname([BUCKET]): [BUCKET].s3.amazonaws.com
DEBUG: ConnMan.get(): creating new connection: https://[BUCKET].s3.amazonaws.com
DEBUG: Using ca_certs_file None
DEBUG: non-proxied HTTPSConnection([BUCKET].s3.amazonaws.com)
DEBUG: format_uri(): /test_1gb.bin
DEBUG: Response: {'status': 400, 'headers': {'x-amz-id-2': 'v42nvyL580BFiM6BNctOxRA2hiSmZk48ByD8NNhEElY2wZvmBC1MEe8j3oTkz+yw3Z2W7Wy5i5g=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'connection': 'close', 'x-amz-request-id': '09EA2DCEF7F6462B', 'date': 'Mon, 16 Feb 2015 13:40:31 GMT', 'content-type': 'application/xml'}, 'reason': 'Bad Request'}
DEBUG: Falling back to signature v2
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:Mon, 16 Feb 2015 13:40:31 +0000\n/[BUCKET]/test_1gb.bin'
s3://[BUCKET]/test_1gb.bin -> ./test_1gb.bin  [1 of 1]
DEBUG: get_hostname([BUCKET]): [BUCKET].s3.amazonaws.com
DEBUG: ConnMan.get(): creating new connection: https://[BUCKET].s3.amazonaws.com
DEBUG: non-proxied HTTPSConnection([BUCKET].s3.amazonaws.com)
DEBUG: format_uri(): /test_1gb.bin
DEBUG: Response: {'status': 400, 'headers': {'x-amz-region': 'eu-central-1', 'x-amz-id-2': 'LqsBVAE7qC0+yq4xdmI5NflgDt9ZEGw4W8XShJaz8wz3FSsNtg48V0ve0LQhFleCSsQ2TE1aX8Y=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'connection': 'close', 'x-amz-request-id': '2D6D3CBE9BCA7CC1', 'date': 'Mon, 16 Feb 2015 13:40:31 GMT', 'content-type': 'application/xml'}, 'reason': 'Bad Request'}
</code>

**Comment by mdomsch** [comment]
Your ~/.s3cfg file has bucket_location = EU (which would be eu-west-1), but
your bucket is in eu-central-1.  It fails the initial call because the
Authorization header has "EU" instead of "eu-central-1" in it.  But it's a
new failure to me that we aren't handling properly (we should just fail at
this point; there's no new information we can get from the request). Then
we fall back to signature v2, and send the request, but that also then
fails, only this time it tells us that we sent the request to the wrong
region (see the x-amz-region header).

The simple solution is to put bucket_location = eu-central-1  into your
~/.s3cfg file, or use --region eu-central-1 on the command line.  Trying to
keep a default of EU while really wanting requests to go to a different
region is what's screwing this up.

Thanks,
Matt

**Comment by mdomsch** [comment]
we fall back to signature v2 because DreamObjects fails the first request
in the exact same way - it doesn't tell us why it failed, so we are
guessing that signature v4 isn't supported, and fall back.  In this case,
it's not the right thing to do, we should just fail.  But aside from adding
more special casing for "if 'amazonaws.com' in host" crap, there isn't a
good automatic solution I can think of today.

The user solution is to set the config file to eu-central-1 or command line
option it, if you're going to talk to a bucket there.

Thanks,
Matt

**Comment by MrCheck** [comment]
Hi Matt,

thanks a lot for your answer! Now it's working fine.
