### ISSUE TITLE
/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/S3/S3.py:487: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

### ISSUE THREAD

**Issue by brunobhr** [s3tools/s3cmd#566]
Hello,
I'm running a s3cmd script from launchd in OSX (as non-root), and I have this error:
/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/S3/S3.py:487: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

I use accentuated characters, my locale is LANG="fr_FR-UTF-8", and my .s3cfg file has "encoding = UTF-8" 

Has anybody any idea?
Thank you,
bruno

**Comment by mdomsch** [comment]
Have you tried running s3cmd from cron by first starting a bash login shell
(bash -l) and then invoking s3cmd from the login shell?  I've found I
needed to do that before.

**Comment by brunobhr** [comment]
Thank you,
I've been struggling for months with running s3cmd from cron...
https://github.com/s3tools/s3cmd/issues/564

Also I'm running OSX.

Any help would be greatly appreciated,
Bruno

**Comment by brunobhr** [comment]
Any idea?
Thank you.

**Comment by fviard** [comment]
Hi,
Looking at the different issues your have raised, I guess that you have encountered a lot of different issues.
At one time, you had a mixup of s3cmd files of different versions.

Otherwise, I would have 2 suggestions for you:
- Set the following in your s3cmd config file: encoding = UTF-8
- I recommand to redirect the output to a file or to dev/nul 
by adding something such as ">> /var/log/crontab.s3cmd.log 2>&1" at the end of your command.
I have noticed for other things that sometimes there was issues with cron when there was an output.

(Otherwise, something that can help you maybe:
http://aaronbonner.io/post/570462273/character-encoding-and-mac-osx)

**Comment by brunobhr** [comment]
Merci Florent,
I've tried all this and more for literally months, and never could run s3cmd as root from a crontab.
But I've solved almost all my problems by running my scripts from launchd as agents.
I highly recommend going that route to whoever wants to have s3cmd scripts ran automatically
on OSX.
I can provide help if someone is interested.
Bruno

**Comment by arisxama** [comment]
Anyone know how to give a solution to this? 

Running s3cmd with --continue-put on folders and filenames UTF-8 (Greek) encoded results in this issue. The command is being executed from bash directly, no scheduler involved.

/usr/lib/python2.7/urllib.py:1288: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))

Best,
Aris

**Comment by fviard** [comment]
Closing this, because I think it is resolved since a few versions.
Please reopen if you are still encountering this issue with a recent release.
