### ISSUE TITLE
s3cmd creates .(point)-Directory if using filelist from `find` with non-absolute path

### ISSUE THREAD

**Issue by janaurka** [s3tools/s3cmd#601]
This is more a suggestion then a real bug.

## Usecase: 

use `find` to find assets, which should get uploaded to S3 within the same directory structure using a non-absolute path.

## Example:

Example `find .` output:
```
./_mysql/js/jquery/src/README
./_mysql/js/jquery/src/jquery
./_mysql/js/jquery/src/jquery/selector-native.js
./_mysql/js/jquery/src/jquery/intro.js
./_mysql/js/jquery/src/jquery/serialize.js
./_mysql/js/jquery/src/jquery/effects.js
```

and then loop the output to `s3cmd` which basically results in something like this:
`s3cmd -P --access_key=$key --secret_key=$secret put $file-with-path s3://$bucket/$file-with-path`

Since `find .` adds `./` to every path, the uploaded file will end up in the given S3 Bucket, in a folder called `.` following the directory structure.

It would be cool if `s3cmd` would cut the `./` in front of the non-absolute path by default, since this is added by the shell and does not contain to the path.

I am aware, that I simply can use something like `s3://$bucket/${file-with-path:2}` in `bash` to trim the first two characters, but I cannot really think of an usecase, why you would want to have a directory called `.`.

This has been tested with `s3cmd version 1.5.2`.

**Comment by fviard** [comment]
Hum, thanks for your feedback, but sadly I don't think that it would have a lot of sense to do that.
For the source maybe, but for the destination, the "./" will be in the middle of the path:
"s3://$bucket/$file-with-path", so you can imagine having things like that:
s3://mybucket/mysubfolder1/second/./here_my_files/blahblah.

It would be strange for us to modify the filename path like that.

But in your case, you also have the following solutions directly from the find command line:
Instead of "file .", you can use the following commands that will not let the ./ :
- "find *" 
- "find . -printf '%P\n'
(Reference: http://stackoverflow.com/questions/2596462/how-to-strip-leading-in-unix-find)
