### ISSUE TITLE
s3cmd cp should preserve ACLs

### ISSUE THREAD

**Issue by stof** [s3tools/s3cmd#648]
When copying publicly accessible files, it would be great that the target also become public accessible instead of being private.
It is possible to specify ``--acl-public`` to force new objects to be public, but this is not intuitive (and it does not play well with copying files where only some of them are public).

**Comment by stof** [comment]
hmm, if I understand things correctly, https://github.com/s3tools/s3cmd/pull/632 might be fixing it.

Is there an ETA for a release including this fix ?

**Comment by fviard** [comment]
@stof If you try with the last version from github, i think that it is merged. the copy of acl is done automatically.

@mdomsch I'm just seeing a regression with that. When using a non aws S3 server, so that don't support ACL, trying to use the ?acl throw a "501 not implemented" error. Failing the copy. I think that an error during the "set acl" should be ignored, at least if it is a 501

**Comment by fviard** [comment]
I did a fix for the error 501 in my case.

@stof  Is it possible for you to confirm that things are working as expected with the last version in master? so we can close the issue.

**Comment by fviard** [comment]
@stof Ping?
