### ISSUE TITLE
with --follow-links, the target of symlinks should have the mime-type of the file they point to, not of the symlink

### ISSUE THREAD

**Issue by MLopez-Ibanez** [s3tools/s3cmd#672]
If I have a symlink "index" pointing to "index.html", the mime-type of index should be the one of index.html when using --follow-links.

**Comment by MLopez-Ibanez** [comment]
This commit fixes it: https://github.com/MLopez-Ibanez/s3cmd/commit/a211864b8daf379d8b40ed96c63e13f86c03965d

**Comment by fviard** [comment]
Thanks for your report, but I'm a little surprised by the fix that you propose.
What does currently mime_magic when you pass a symlink?
I guess that it use the filename to determine the type based on the extension, so in your case you don't see anything.

But in that case, I'm a little worried of possible side effects with your patch.
Lets suppose that I have "index.html" that is a symlink to my-index.txt.
With your page the mime type would be determined based on ".txt" instead of ".html" as currently.

(Note: that you can also manually set a mime type for a specific file like the "index" in your case.)

**Comment by MLopez-Ibanez** [comment]
What I'm trying to do is to have clean links (that is, links without .html).

I'm not sure why you would have a html file with extension .txt

However, there are cases when you may have a file without extension and you want to keep this link working even if the file type of the target of the symlink changes.

**Comment by MLopez-Ibanez** [comment]
Others like me have struggled to do this in S3:

http://stackoverflow.com/questions/23463679/s3-static-pages-without-html-extension

http://serverfault.com/questions/650704/url-rewriting-in-amazon-s3

URL rewriting simply doesn't scale and it cannot be easily automatized.

This is something so easy in Apache:

http://stackoverflow.com/questions/2836400/clean-urls-for-static-html-files-with-htaccess-and-mod-rewrite

**Comment by fviard** [comment]
Should be resolved in Master with:
https://github.com/s3tools/s3cmd/commit/d7b60b894b1d58d9dd66ea603d3438f0e576589b
I hope that the change in behavior will not have bad side effects for some persons.
But what you proposed looks indeed to be the most logic behavior.
