### ISSUE TITLE
For large syncs, what's "enough" RAM?

### ISSUE THREAD

**Issue by wytcld** [s3tools/s3cmd#732]
Ran an initial sync where the system running it was Linux copying from a Samba mount of a Windows directory tree with about 400G of smallish files - in other words many thousands. It ran fine. But when I set up to do subsequent syncs from cron, the first time around ran through the 4 G RAM and the 8 G swap, and started doing the OOM dance. Second time around too.

I've read several of the OOM reports here, and saw one suggestion that maybe 8 G RAM is called for. But considering that I ran through 12 G (including the swap) here, I'm wondering what the practical requirements are for setting this up to handle large syncs without having to worry about OOM fun. Is there any rule of thumb for calculating that?

Or is the right way to do it to write another script to break up the job, feeding much smaller chunks of it to s3cmd? Even so, it would be good to have a rough notion of how many files need how much free RAM for s3cmd to be happy.

**Comment by fviard** [comment]
It is a good but hard question.
Currently, for the sync, s3cmd create two lists in memory: local files and remote files.
Then, it does a comparison between them to only have in the end the list of files to add/delete/update.
So the critical step for memory is when the 2 lists are fulfilled.
It is sad that it is all in memory, and is something I would like to have fixed in some future, but it requires a lot of work.

So, if you want to be able to guess a minimum for the memory needed:
- Local list store for each local file, a few small metadata but the biggest things are around 2 times the filepath (name included but relative to the local base path)
- Remote list store for each remote file, a few small metadata but around 3 times the remote filepath (uri like) and the base path of the remote location.

So with that, you can see that it depends a lot of your file tree hierarchy and the length of your filenames.
Note: for the remote list, I think that there is still room for easy optimization. (I plan to remove soon at least one copy of the filepath).

So, for your case, the best optimization will indeed be to split your task in smaller chunks, like if you can run the jobs on each subfolder instead of directly at the base path. The deeper you go in subfolders, the less will be required.

**Comment by wytcld** [comment]
I'm now suspecting the main cause of the OOM experience may have been having the buckets also mounted with s3fs, which I've been using just as a more convenient way to browse sections of the backups. It's got a serious memory leak: https://github.com/s3fs-fuse/s3fs-fuse/issues/340. Found it on an idle VM with 4 G RAM and 8 G swap exhausting all of that, doing nothing but having a couple of large buckets mounted despite that nobody and nothing was accessing those buckets through those mounts.
