### ISSUE TITLE
s3cmd sync with sha256 hash instead of md5 hash

### ISSUE THREAD

**Issue by albarki** [s3tools/s3cmd#756]
Hello 
 `s3sync` check By default a md5 checksum and file size to know if the file is changed or not.
My question is, how to use sha256 instead of md5?

**Comment by bengoodwyn** [comment]
This feature uses the ETag header provided by Amazon's S3 implementation for server-side MD5 storage. Depending on the upload and encryption mechanisms S3 stores the MD5 of the object in the ETag. S3 does not have an option for storing a SHA256 of the object content; however, this could be added as custom metadata. There is a bit of development work that would be required to synchronize using SHA256 sums rather than MD5 sums including adding the custom metadata on upload and comparing SHA256 sums. The option in s3cmd is to either use MD5 or only use the file's size. Of course, using only the file's size is dangerous because the modification of the file without truncation or append is not detected as a change.

What is your use case that has you concerned with MD5 used for synchronization?

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

**Comment by sfxworks** [comment]
FIPS on RHEL 8

**Comment by fviard** [comment]
@sfxworks FYI, a change was just pushed to MASTER to support FIPS on RHEL8
