### ISSUE TITLE
--config given full path fails

### ISSUE THREAD

**Issue by acidjazz** [s3tools/s3cmd#801]
```
[root@ip-172-31-12-38 ec2-user]# pwd
/home/ec2-user
[root@ip-172-31-12-38 ec2-user]# s3cmd --config='/home/ec2-user/.s3cfg' ls
ERROR: S3 error: 403 (InvalidAccessKeyId): The AWS Access Key Id you provided does not exist in our records.
[root@ip-172-31-12-38 ec2-user]# s3cmd --config='~/.s3cfg' ls
** buckets are listed **
```

**Comment by fviard** [comment]
I did not encounter any issue with my own testing.
But I see that you are logged in as root, so your "home" targeted by "~" could be root's home.
Try the following cmd: "realpath ~"
If think that it will target something like /root .
So I guess that you have 2 .s3cfg files, one inside /root and the other one inside /home/ec2-user. And the last one doesn't have correct access/key values.

**Comment by ewoks** [comment]
@fviard related question:
should relative path work too? e.g. if s3config is in the execution folder and I run it like 
`s3cmd -c .s3cfg ls `
Please let me know about expected behaviour, as I face weird issues when trying like this and user home folder doesn't exist. Somehow host value "falls back" to us.s3.amazon.com or similar, despite .s3cfg having other host.

**Comment by fviard** [comment]
In case your question was never resolved, normally yes the "-c" option will look in the "current working directly" for relative paths.
