### ISSUE TITLE
I am unable to put the file on as attachment or application/octet-stream 

### ISSUE THREAD

**Issue by ejazhashmi** [s3tools/s3cmd#832]
I am facing the issue that when ever i upload the file specially .csv and hit on the browser it allow to show it content. 

It appears the s3cmd is not able to change the content-type.

s3cmd --content-type=attachment --acl-public put accessKeys.csv s3://mys3bucket/

s3cmd --content-type=application/octet-stream  --acl-public put accessKeys.csv s3://mys3bucket/

What i want to achieve is to upload the file and when the file hit on the browser it ask to download the file not to show it's contents

Can you please guide me 

Regards
Syed Ejaz

**Comment by fviard** [comment]
If you still have this problem, the issue is that you should have used:
content-disposition=attachement
(content-disposition and not content-type)
In that case, content-type is irrelevant.

But, that being said, the content-disposition is just used when doing an signed url for the moment, you should be able to do what you want by manually setting the header
```
--add-header='Content-Disposition: attachment'
```
