### ISSUE TITLE
s3cmd stops working after some time (on raspberry pi)

### ISSUE THREAD

**Issue by clemyvi** [s3tools/s3cmd#836]
It happens 'out of the blue' after a few months when the program is working fine.
Suddenly I get the following error when I run any s3cmd command: 

> File "usr/bin/s3cmd", line 2533, in <module> 
> except (ParameterError, InvalidFileError), e: 
> NameError: name 'ParameterError' is not defined

I tried to reinstall s3cmd but problem still persists.
Any idea of what to do ?

**Comment by fviard** [comment]
I think that you have an old version.
You should upgrade.
First, you can try to run s3cmd with "-d" flag to have more debug output.

My best guess regarding your problem would be more something like 2 different versions installed on the system. For example with parts of it manually installed and some other automatically updated by the system.

**Comment by clemyvi** [comment]
Thanks for your suggestion.
I will check the double installation problem but it seems unlikely to be the problem here as nothing was installed between the time it was working and the time it wasn't working. 
Nothing gets auto-updated on raspberry pi.

One oddity I wanted to mention is that I have s3cmd installed on an SD card that has been cloned several times, so exact same config of s3cmd is being used on different machines. 
Could this be creating the problem by any chance?

**Comment by fviard** [comment]
@clemyvi you have to take care that on the installed system, there is one "py" that is installed like a binary in /usr/bin/ (s3cmd) and the rest that is inside python modules dir like /usr/lib/python2.7/site-packages (S3). Both of them has to be in sync. So, copying things manually, it is possible to just override one and not another.

If you installed things with "setup.py install", it is also possible that the "s3cmd" command file was well installed, but the module were installed in a conflicted dir.
Example is that in /usr/ib/python2.7/site-package, you would find a "S3" folder coming from the "debian" original installation and something like a "s3cmd-..dfsfsdg.egg/" with the new S3 installed inside. In that case the original S3 module folder could accidentally be used instead of the new one.

**Comment by fviard** [comment]
Please re-open if you are still encountering this issue and don't think that it comes from your setup/operations.
