### ISSUE TITLE
Data loss when moving multiple files

### ISSUE THREAD

**Issue by guygurari** [s3tools/s3cmd#854]
I would like to move all tar files (`1.tar`, `2.tar`, ...) into a subdirectory `dir`, so I run the following.

`s3cmd mv s3://bucket/*.tar s3://bucket/dir`

In practice this takes each tar file and renames it to a file called `dir`. This leads to data loss because each rename operation overwrites the file created by the previous rename.

Data loss occurs because S3 allows both a directory called `dir` and a file called `dir` to exist at the same time. The command above expands into the following sequence of commands.

`s3cmd mv s3://bucket/1.tar s3://bucket/dir`
`s3cmd mv s3://bucket/2.tar s3://bucket/dir`
`s3cmd mv s3://bucket/3.tar s3://bucket/dir`
`...`

Each tar file gets renamed `dir`, and each subsequent command overrides the file created by the previous one.

A workaround is to run the command with a trailing slash, like this.

`s3cmd mv s3://bucket/*.tar s3://bucket/dir/`

**Comment by guygurari** [comment]
The problem seems to be in `s3cmd` in the function `subcmd_cp_mv`:

```
for key in remote_list:
    if destination_base.endswith("/"):
        remote_list[key]['dest_name'] = destination_base + key
    else:
        remote_list[key]['dest_name'] = destination_base
```

If there is no trailing slash, the files all get moved to `destination_base`. To me, this seems like unexpected and dangerous behavior. For comparison, UNIX `mv` would give an error in a similar situation (trying to rename multiple files into a single file). I'd be happy to add a pull request that fixes this, but is there a good reason for the existing behavior?

**Comment by fviard** [comment]
Thank you for this report.
indeed that behavior is not very great.

Something should probably done like in "cmd_sync_remote2local" where an error is returned if you try to use multiple source with a destination that has no "/".

As you noticed, a big issue is that we don't know if source/dest are directories or files.
Looking at the code in subcmd_cp_mv, that is currently a little more complicated than this short snippet of code. If the "recursive" flag is set by config or command line, there is one behavior, otherwise there is another behavior that is the one that you noticed.

It is not great if you want my opinion, but before changing that we have to balance "the future" and the "legacy" of people scripts/usage that could rely on the current behavior.

Patches are very welcome.
Just try to evaluate all the cases that are possibles: multiple sources that are dirs; that are files; just one files that is "renamed" etc...

**Comment by guygurari** [comment]
Okay, I'll try to submit a patch. By the way, I think the code you are referring in `cmd_sync_remote2local` has a bug:

```
    if not destination_base.endswith(os.path.sep):
        if fetch_source_args[0].endswith(u'/') or len(fetch_source_args) > 1:
            raise ParameterError("Destination must be a directory and end with '/' when downloading multiple sources.")
        elif fetch_source_args[0].endswith(u'/'):
            fetch_source_args[0] += u'/'
```

The `elif` branch can never get executed because the code has this form:

```
if A or B:
    ...
elif A:
   # unreachable
```

I don't understand the intended meaning though.

**Comment by fviard** [comment]
You are right. Looks like to be wrong and could be removed.
After a lot of thinking, I don't see what was the intended behavior or possible typo.
