### ISSUE TITLE
--delete-removed Usage documentation is inaccurate

### ISSUE THREAD

**Issue by cthorley** [s3tools/s3cmd#872]
The [man page](http://s3tools.org/usage) for s3cmd reports the behavior of `--delete-removed` as:

`Delete remote objects with no corresponding local file`

This is inaccurate.  The behavior of this option is:

`Delete destination objects with no corresponding source file`

This verbiage is consistent with the explanation of other options, such as `--skip-existing`:

`Skip over files that exist at the destination`

This is particularly confusing given that the example templates used throughout the Commands section of the man page use the `s3://BUCKET` vs. `LOCAL_DIR` convention for many of the items.

For what it's worth, I don't find `--delete-removed` to be a particularly intuitive flag for its behavior.  It seems that syncs with this behavior are called "destructive syncs" as a matter of convention in a number of contexts.  I would suggest that the flag be renamed `--destructive` if the opportunity to update the interface presents itself.

**Comment by fviard** [comment]
Fixed. Thank you for your report.
for the "destructive", i'm not so fan because it looks scary and is not either complete.
As files can be "updated", even if "delete" is not used, the sync could be considered "destructive".

Anyway, improvements of the documentation (and also of the rest) are welcomes, so don't hesitate to contribute with patches/pull requests if you can :-)
