### ISSUE TITLE
s3cmd uses MD5

### ISSUE THREAD

**Issue by rkeene** [s3tools/s3cmd#876]
Currently "s3cmd" uses MD5 a lot internally.  This causes several problems:

1. FIPS 140-2 forbids MD5, so using "s3cmd" with GovCloud is effectively impossible
2. MD5 is a relatively weak cryptographic hash

I understand that the ETag response header may contain an MD5, but s3cmd already stores a secondary hash in an additional header (x-amz-meta-s3cmd-attrs).  This hash is also an MD5 and could be changed to something more modern and usable on GovCloud.

Is there any benefit to using the ETag (which may or may not be an MD5) over the s3cmd-attrs header ?

**Comment by fviard** [comment]
The use of MD5 is only coming from the S3 protocol relying on it.
md5 in x-amz-meta-s3cmd-attrs usage is mostly for "mutlipart files", ie files that are uploaded in multiple logical chunks. The etag is somehow scrambled as it could only be determined by knowing the chunk size and number of chunks of a file. The custom attribute is there to compensate that.

Some other hash could be used in the custom attribute, but it would not make a lot of sense and a safe code to mix things.

I don't have knowledge of the FIPS 140-2, so I can be wrong, but here is what I think:
- There is an amazon s3 endpoint dedicated to US Gov usages. And I think that that endpoint use the same protocol, so I guess that s3cmd should be usable for GovCloud regarding this aspect.
 - I suppose that the FIPS only address "cryptographic hashes" as what to be used in "cryptographic functions". Here, the md5 is not used for that purpose. It is only used as "file change" comparison. So at worse a file would be modified but because of a collision the md5 would stay the same and so the file would not be updated. (I don't know of hack/attacks that could be linked to that).
- In amazon S3 and what is used by s3cmd by default, it is now a "sha256" based hmac cryptographic function that is used for signature and communication integrity checks. So that should be ok for the FIPS 140-2 ?

And to reply to your last question. The ETag is provided directly for each "entries" in LIST requests, whereas we have to issue an individual HEAD request for each object to get custom metadata like the s3cmd-attrs. So, that is avoided as much as possible to be faster and issue less requests.

**Comment by fviard** [comment]
To follow up on the subject, it looks like that fips doesn't forbid to use md5 for non cryptographic functions like for the ETag. But that it is just the system itself that can block its usage in "fips" mode. that's why enabling this option on windows for example is not recommended:
https://blogs.technet.microsoft.com/secguide/2014/04/07/why-were-not-recommending-fips-mode-anymore/

https://github.com/jshttp/etag/issues/17

**Comment by plastikman** [comment]
Your comment and point is valid however the reality is if you are working with the government you are required to have your servers in FIPS mode or you are required to have all traffic traverse out your boundary through a FIPS enabled device.  

I would love to use s3cmd on my FIPS and non FIPS servers instead of having to have a separate set of scripts for my FIPS and non FIPS machines.


CentOS/RHEL have added an exception to python 2.7.5-18+ to allow MD5 in hashlib to be used for non crypto "usedforsecurity=False" perhaps this could be implimented as a patch for CentOS/RHEL while in FIPS mode?

https://git.centos.org/blob/rpms!python.git/b7580ac42e9a243f3eb2039c91b7ca3daa4656be/SOURCES!00146-hashlib-fips.patch

https://code.djangoproject.com/ticket/28401

https://bugs.python.org/issue9216
