### ISSUE TITLE
Seeing Timeouts in S3 Uploads

### ISSUE THREAD

**Issue by preet1309** [s3tools/s3cmd#877]
While Trying to Backup our Database to S3 Buckets We are consistently Seeing timeouts
Please go through the stack trace below

If this is a known issue please suggest a viable workaround

```
Problem: error: [Errno 110] Operation timed out
S3cmd:   1.6.1
python:   2.7.12 (default, Jun 29 2016, 09:11:45) 
[GCC 5.3.0]
environment LANG=None

Traceback (most recent call last):
  File "/opt/s3cmd/s3cmd", line 2996, in <module>
    rc = main()
  File "/opt/s3cmd/s3cmd", line 2915, in main
    rc = cmd_func(args)
  File "/opt/s3cmd/s3cmd", line 1837, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/opt/s3cmd/s3cmd", line 1811, in cmd_sync_local2remote
    ret = _single_process(args[:-1])
  File "/opt/s3cmd/s3cmd", line 1569, in _single_process
    return _child(destination_base, source_args)
  File "/opt/s3cmd/s3cmd", line 1673, in _child
    remote_list, dst_exclude_list, remote_total_size = fetch_remote_list(destbase_with_source_list, recursive = True, require_attribs = True)
  File "/opt/s3cmd/S3/FileLists.py", line 457, in fetch_remote_list
    objectlist, tmp_total_size = _get_filelist_remote(uri, recursive = True)
  File "/opt/s3cmd/S3/FileLists.py", line 394, in _get_filelist_remote
    recursive = recursive, uri_params = uri_params)
  File "/opt/s3cmd/S3/S3.py", line 327, in bucket_list
    for truncated, dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params, limit):
  File "/opt/s3cmd/S3/S3.py", line 358, in bucket_list_streaming
    response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params, max_keys)
  File "/opt/s3cmd/S3/S3.py", line 389, in bucket_list_noparse
    response = self.send_request(request)
  File "/opt/s3cmd/S3/S3.py", line 1235, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "/opt/s3cmd/S3/ConnMan.py", line 249, in get
    conn.c.connect()
  File "/usr/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 110] Operation timed out
```

Thanks

Preet

**Comment by fviard** [comment]
Here the timeout is at the establishment of the connection.
(s3cmd doesn't do any retry for that stage)

The most probable cause is that you have network connectivity issues.
On a case not related to s3cmd, I had that kind of issue, and it was faulty network switches. 
In fact, by testing, I noticed that a lot of small network switches, like cheap netgear one age very badly.
If you want to test that, on your server, try to let the following command run of a few minutes:
"ping s3.amazonaws.com"
After that you interrupt it with "ctrl+c" and you can look if there are "packet loss". That would be a bad sign.

**Comment by preet1309** [comment]
Hi,

We are running this in a complete AWS environment.
nodes from which s3cmd is executed is in AWS and there is a VPC endpoint for the cluster to connect to S3
We are still seeing timeouts intermittently, or as you suggested, connection errors

Any Ideas what may be causing this or any recommendations on how we can improve s3 upload from our AWS cluster

**Comment by rsyncnet** [comment]
We (rsync.net) are seeing this in our environment as well.  Running s3cmd is producing a lot of timeouts ... we connect to S3 just fine but then start to see:

WARNING: Retrying failed request: (filename)
WARNING: Waiting 3 sec...
(retries file again)
ERROR: SSL certificate verification failure: ('The read operation timed out',)

We do have the default timeout set in our config file:

socket_timeout = 300

We have no packet loss to AWS/S3 ...

How can we specify to be less fragile to these timeout, or perhaps specify to retry more than once when it fails ?

**Comment by fviard** [comment]
@rsyncnet Are you seeing these on aws ec2 instances? And using iam credentials?

It is not related to my idea, but just in case, couldn't it be for you something like what is described here:
https://forums.aws.amazon.com/thread.jspa?threadID=227465

**Comment by rsyncnet** [comment]
@fviard No, the way that rsync.net customers (not us) use s3cmd is they call it, over SSH, in their rsync.net account - like this:

  ssh user@rsync.net s3cmd get s3://rsync/mscdex.exe

So they are running s3cmd, on an rsync.net system (actual metal servers we own, not part of a cloud), that points to the s3 bucket they specify and uses the settings in their config file that is in their rsync.net root directory.

Authentication is the access key / secret key that they define in their s3cmd config file.

Latest version of s3cmd produces a lot of this:

WARNING: Retrying failed request: /dir/file.zip ('')
WARNING: Waiting 3 sec...
download: 's3://dir/filezip' -> './s3backup/dir/file.zip_061820170204AM..zip' [1 of 42]
   874315776 of 17092665305     5% in  391s     2.13 MB/s  failed

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:

https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Thank you.

**Comment by fviard** [comment]
@rsyncnet Could it be possible for you to provide me with credentials of such a setup so that I can investigate this?

**Comment by xavier268** [comment]
I am having  a timeout issue with some similarity here, although the detail stack is not exactly the same.

My context is a s3cmd sync command from a bare metal install of centos 6 on a small server, for a large directory (19G, 165K files), where very few files have changed. I also process smaller directories and that works fine.

I followed the suggestion of ping-ing s3.amazon.com for appx 30mns and there was no packet loss.

I tried setting socket_timeout  to 3000 with no result.

It is very surprising to me that the timeout is happening every time so far (repeatable 4-5 times in a row on my configuration), and EXACTLY at the same moment, AFTER the moment when the list of what needs to be done has been established, but BEFORE any file is actually uploaded or removed. You can see that from the two successive example below, they were run with appx 1 hour difference, and provide the same summary file count. No file were changed between the last two runs.

I was never faced with this previously, until I upgraded to v6.2.1, and then immediately to 2.0.0 to see if that would fix it. My data volume have probably slightly increased since my last backup, but nothing really significant, certainly less than a few hundred files and below 100M. Can this be a coincidence ?

Thank you,

Xavier 

See details below :

*************** EXAMPLE 1 ****************
.../...
INFO: [155000/165196]
INFO: [156000/165196]
INFO: [157000/165196]
INFO: [158000/165196]
INFO: [159000/165196]
INFO: [160000/165196]
INFO: [161000/165196]
INFO: [162000/165196]
INFO: [163000/165196]
INFO: [164000/165196]
INFO: [165000/165196]
INFO: Retrieving list of remote files for s3://bup3.gandillot.com/sc420/home/xavier/ ...
INFO: Forwarding request to eu-west-1
INFO: Found 165196 local files, 166126 remote files
INFO: Verifying attributes...
INFO: Summary: 17 local files to upload, 0 files to remote copy, 944 remote files to delete

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/bin/s3cmd sync --acl-private -H -r -p -v --delete-removed /home/xxxxx/ s3://bup3.ggggggggg.com/sssss/home/xxxxx/
Problem: error: [Errno 110] Connection timed out
S3cmd:   2.0.0
python:   2.6.6 (r266:84292, Aug 18 2016, 14:53:48) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
environment LANG=fr_FR.utf8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2996, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2915, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1837, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/usr/bin/s3cmd", line 1811, in cmd_sync_local2remote
    ret = _single_process(args[:-1])
  File "/usr/bin/s3cmd", line 1569, in _single_process
    return _child(destination_base, source_args)
  File "/usr/bin/s3cmd", line 1728, in _child
    subcmd_batch_del(remote_list = remote_list)
  File "/usr/bin/s3cmd", line 710, in subcmd_batch_del
    _batch_del(remote_list)
  File "/usr/bin/s3cmd", line 686, in _batch_del
    response = s3.object_batch_delete(to_delete)
  File "/usr/lib/python2.6/site-packages/S3/S3.py", line 718, in object_batch_delete
    self.object_batch_delete_uri_strs(uris)
  File "/usr/lib/python2.6/site-packages/S3/S3.py", line 748, in object_batch_delete_uri_strs
    response = self.send_request(request)
  File "/usr/lib/python2.6/site-packages/S3/S3.py", line 1252, in send_request
    conn.c.request(method_string, uri, request.body, headers)
  File "/usr/lib/python2.6/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.6/site-packages/S3/Custom_httplib27.py", line 152, in httpconnection_patched_send_request
    self.endheaders(body)
  File "/usr/lib/python2.6/site-packages/S3/Custom_httplib27.py", line 179, in httpconnection_patched_endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.6/site-packages/S3/Custom_httplib27.py", line 211, in httpconnection_patched_send_output
    self.send(message_body)
  File "/usr/lib/python2.6/httplib.py", line 810, in send
    self.sock.sendall(str)
  File "<string>", line 1, in sendall
error: [Errno 110] Connection timed out

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


*************** EXAMPLE 2 (appx an hour later) *****************
.../...
INFO: [158000/165196]
INFO: [159000/165196]
INFO: [160000/165196]
INFO: [161000/165196]
INFO: [162000/165196]
INFO: [163000/165196]
INFO: [164000/165196]
INFO: [165000/165196]
INFO: Retrieving list of remote files for s3://bup3.ggggggggg.com/sssss/home/xxxxx/ ...
INFO: Forwarding request to eu-west-1
INFO: Found 165196 local files, 166126 remote files
INFO: Verifying attributes...
INFO: Summary: 17 local files to upload, 0 files to remote copy, 944 remote files to delete

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/bin/s3cmd sync --acl-private -H -r -p -v --delete-removed /home/xxxxxx/ s3://bup3.ggggggggg.com/sssss/home/xxxxxx/
Problem: error: [Errno 110] Connection timed out
S3cmd:   2.0.0
python:   2.6.6 (r266:84292, Aug 18 2016, 14:53:48)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
environment LANG=fr_FR.utf8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2996, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2915, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1837, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/usr/bin/s3cmd", line 1811, in cmd_sync_local2remote
    ret = _single_process(args[:-1])
  File "/usr/bin/s3cmd", line 1569, in _single_process
    return _child(destination_base, source_args)
  File "/usr/bin/s3cmd", line 1728, in _child
    subcmd_batch_del(remote_list = remote_list)
  File "/usr/bin/s3cmd", line 710, in subcmd_batch_del
    _batch_del(remote_list)
  File "/usr/bin/s3cmd", line 686, in _batch_del
    response = s3.object_batch_delete(to_delete)
  File "/usr/lib/python2.6/site-packages/S3/S3.py", line 718, in object_batch_delete
    self.object_batch_delete_uri_strs(uris)
  File "/usr/lib/python2.6/site-packages/S3/S3.py", line 748, in object_batch_delete_uri_strs
    response = self.send_request(request)
  File "/usr/lib/python2.6/site-packages/S3/S3.py", line 1252, in send_request
    conn.c.request(method_string, uri, request.body, headers)
  File "/usr/lib/python2.6/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.6/site-packages/S3/Custom_httplib27.py", line 152, in httpconnection_patched_send_request
    self.endheaders(body)
  File "/usr/lib/python2.6/site-packages/S3/Custom_httplib27.py", line 179, in httpconnection_patched_endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.6/site-packages/S3/Custom_httplib27.py", line 211, in httpconnection_patched_send_output
    self.send(message_body)
  File "/usr/lib/python2.6/httplib.py", line 810, in send
    self.sock.sendall(str)
  File "<string>", line 1, in sendall
error: [Errno 110] Connection timed out

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**********************************
Configuration file  :  /root/.s3config
**********************************

[default]
access_key = EDITEDFORPRIVACY
bucket_location = EU-west-1
cloudfront_host = cloudfront.amazonaws.com
cloudfront_resource = /2010-07-15/distribution
default_mime_type = binary/octet-stream
delete_removed = False
dry_run = False
encoding = UTF-8
encrypt = False
follow_symlinks = False
force = False
get_continue = False
gpg_command = /usr/bin/gpg
gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_passphrase =
guess_mime_type = True
host_base = s3.amazonaws.com
host_bucket = %(bucket)s.s3.amazonaws.com
human_readable_sizes = False
list_md5 = False
log_target_prefix =
preserve_attrs = True
progress_meter = True
proxy_host =
proxy_port = 0
recursive = False
recv_chunk = 4096
reduced_redundancy = False
secret_key = EDITEDFORPRIVACY
send_chunk = 4096
simpledb_host = sdb.amazonaws.com
skip_existing = False
socket_timeout = 3000
urlencoding_mode = normal
use_https = False
verbosity = WARNING

**Comment by fviard** [comment]
I'm still investigating this issue but it is still quite mysterious to me.
The timeouts of the different reporters.

**Comment by xavier268** [comment]
I confirm that, with my configuration, the time out does not crash (only warning + retry for the first file) with version 1.5.2, but does crash on 1.6.0, 1.6.1 and 2.0.0.

Xavier

**Comment by preet1309** [comment]
@fviard 
We are seeing this issue repeatedly on docker 1.11.3 as well and s3cmd 1.6.1 and 2.0.0
Especially when the data size is large

Any updates on this??

**Comment by liangway** [comment]
+1
