### ISSUE TITLE
ETag shouldn't be used for MD5 verification

### ISSUE THREAD

**Issue by EgoAleSum** [s3tools/s3cmd#880]
This is connected with this issue I've filed for Minio: https://github.com/minio/minio/issues/4537

s3cmd considers the ETag field to be the file's md5, but  "the ETag may or may not be an MD5 digest of the object data" (see: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html ) This is causing issues with tools such as Minio in gateway mode: `s3cmd put` always fails with checksum errors.

The `--no-check-md5` option doesn't seem to work with the `put` command.

**Comment by krishnasrinivas** [comment]
s3cmd devs, for MD5 verification can you guys use `Content-MD5` header instead of ETag? When `minio` is run in s3-gateway mode it makes Azure Blob Storage look like S3. Azure stores ETag that looks like `0x8D4B2AE97754E88` which is not MD5.

According to RFC https://tools.ietf.org/html/rfc7232#section-2.3 ETag is an opaque string. AWS-S3 for single part PUT just uses MD5 for ETag. For multipart it's not MD5.

Using Content-MD5 header instead of ETag for MD5 verification can make s3cmd work with Azure Blob Storage using minio.

**Comment by fviard** [comment]
Hum, interesting question.
@EgoAleSum the --no-check-md5 doesn't work in your case because it is designed to avoid the cost of calculating md5 of all the files to select what to update in a sync, but not the less expensive one of ensuring that files were correctly transferred

@krishnasrinivas The idea of using content-md5 is interesting, but i'm concerned with the following point:
- Would most of the s3 custom servers implementations support this? How to know if it is not the case and so still spot corruption? There could probably be an option flag, but that is really implementation dependent and would not means a lot to normal users. 

Currently, too much in the S3 protocol assume that the etag is the hash except some special cases:
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html

At this subject, I'm curious to know how you dealt with "multipart uploads" as you are supposed to complete them with the list of etags?

@krishnasrinivas If modifications are possibles on your side, I would suggest an alternative:
If you don't have access to the md5 from azure and so that you can't "replace" the etags with it on the fly, what do you think about doing the following:
- Append a "-1" to the end of the etag coming from azure. Like (0xDE32425BFA-1).
(Maybe even remove the 0x at the beginning).
So, it would look like a multipart file of "1" chunk, and would trigger all the codes that are used to "ignore" the etag for multipart files and so using custom meta data to check hashes.
- On s3cmd side, I could had a fix to ignore checking the md5 after "upload" if there is a "-" in the server etag. That is what is currently done for download.

**Comment by krishnasrinivas** [comment]
@fviard thanks for the response!

> @krishnasrinivas The idea of using content-md5 is interesting, but i'm concerned with the following point:

> Would most of the s3 custom servers implementations support this? How to know if it is not the case and so still spot corruption? There could probably be an option flag, but that is really implementation dependent and would not means a lot to normal users.

AWS-S3 definitely supports it. Any serious S3 alternative would also support it.

Content-MD5 is a HTTP standard for MD5 sum: http://www.ietf.org/rfc/rfc1864.txt
ETag is just an opaque string: https://tools.ietf.org/html/rfc7232#section-2.3

i.e Chances are higher that S3 alternatives support Content-MD5 verification than return MD5 for ETag.

Hence s3cmd will be more inter-operable if you use Content-MD5 for MD5 verification instead of ETag.

> At this subject, I'm curious to know how you dealt with "multipart uploads" as you are supposed to complete them with the list of etags?

Multipart worked fine, Maybe s3cmd does not use ETag for MD5 in multipart uploads?

> @krishnasrinivas If modifications are possibles on your side, I would suggest an alternative:
If you don't have access to the md5 from azure and so that you can't "replace" the etags with it on the fly, what do you think about doing the following:

> Append a "-1" to the end of the etag coming from azure. Like (0xDE32425BFA-1).
(Maybe even remove the 0x at the beginning).

We cannot not modify the ETag because if clients use `If-Match` and `If-None-Match` precondition with Azure directly it will mismatch.

**Comment by fviard** [comment]
@krishnasrinivas Let's say that you had a "-1" suffix to the ETag, you can add/strip to If-match, if-none-match stage?
I have been thinking about this issue, and realized that the "Content-MD5" will not be enough to fix the issue: At sync stage or download, we will not be able to differentiate an ETag md5 and from an non md5 azure one. Probably we can parse on "0x", but that would be really ugly as related to azure protocol that is unrelated to s3.

**Comment by krishnasrinivas** [comment]
> @krishnasrinivas Let's say that you had a "-1" suffix to the ETag, you can add/strip to If-match, if-none-match stage?

If the client tries to do a GET on Azure directly using `If-Match` then we won't be able to strip the "-1" suffix and hence cause problems.

> I have been thinking about this issue, and realized that the "Content-MD5" will not be enough to fix the issue: At sync stage or download, we will not be able to differentiate an ETag md5 and from an non md5 azure one. Probably we can parse on "0x", but that would be really ugly as related to azure protocol that is unrelated to s3.

For sync, I see that s3cmd does not use ETag and instead use `X-Amz-Meta-S3cmd-Attrs` metadata:
```
X-Amz-Meta-S3cmd-Attrs: uid:1000/gname:krishna/uname:krishna/gid:1000/mode:33204/mtime:1498438105/atime:1498438115/md5:281ed1d5ae50e8419f9b978aab16de83/ctime:1498438105
```

This metadata contains md5sum information. I think s3cmd uses this as md5sum and not ETag? Am I missing anything?

**Comment by fviard** [comment]
We can only get this info for with a costly individual "HEAD" request on the resource.
Not during object list request. There is just the "ETag" in the list.
So we do a "HEAD" only on resources that are identified as multi-part (ie having the "-" char in their ETag). And for them only we issue the HEAD request to get the real md5 in custom meta.

**Comment by krishnasrinivas** [comment]
Thanks @fviard I will check with my team and see if we can do anything from our side to make it work.

**Comment by fviard** [comment]
@krishnasrinivas Btw, just as a suggestion for evolution of Minio for the normal S3 behavior:
If the "list objects" could directly return the custom metadata or a new field with the real md5 even for multipart files, that would be a very great improvement in efficiency compared to aws s3.
So, that would allow to avoid a lot of extra traffic by not having to issue individual "HEAD" requests for multipart uploaded files.

**Comment by krishnasrinivas** [comment]
> If the "list objects" could directly return the custom metadata or a new field with the real md5 even for multipart files

We can't add new fields to the list response @fviard it will have to conform to S3 spec.

> Append a "-1" to the end of the etag coming from azure. Like (0xDE32425BFA-1).
(Maybe even remove the 0x at the beginning).

We are thinking of implementing this.

**Comment by krishnasrinivas** [comment]
> Append a "-1" to the end of the etag coming from azure. Like (0xDE32425BFA-1).

We implemented this @fviard but still getting:

```
DEBUG: MD5 sums: computed=73c2ee0acb590362c0ac3740f8c39523, received="0x8D4C4CCE4CF5281-1"
```

**Comment by EgoAleSum** [comment]
@fviard Bumping this up - is there any update on your end?

**Comment by harshavardhana** [comment]
@fviard when are you thinking of a new release?

**Comment by EgoAleSum** [comment]
Thanks for fixing this!

**Comment by fviard** [comment]
@EgoAleSum You can confirm that it is now working well for you with that? It is a nice feature in the end to be able to do that with Minio.

**Comment by fviard** [comment]
@harshavardhana I will try to do a new release this week.

**Comment by harshavardhana** [comment]
> @harshavardhana I will try to do a new release this week.

Thanks a lot :+1:

**Comment by EgoAleSum** [comment]
@fviard Happy to test this -- how can run the app from the latest source?

**Comment by fviard** [comment]
@EgoAleSum for s3cmd, you can "clone" the current last version on your computer:
git clone https://github.com/s3tools/s3cmd.git
(or from github you can also download a zip of it).

Normally you can go inside the "cloned" folder and run directly the ./s3cmd there.
There might be a chance that when running, you have a conflict with an already installed s3cmd on your machine when trying to running it. In that case, the best is probably to run it inside a python "virtualenv".
For Minio, I don't know if they provide nightlies of their binaries. Otherwise, you would have to clone it as well and rebuild it.

**Comment by EgoAleSum** [comment]
@fviard Thanks. Using `minio/minio:latest` (Docker container), I am getting this error:

`ERROR: S3 error: 400 (InvalidArgument): Your metadata headers are not supported.`

I assume it's because @harshavardhana 's patch hasn't been merged yet. As soon as that's available in a Docker container I'll be happy to test again.

**Comment by jmaitrehenry** [comment]
@fviard @harshavardhana  I just made some tests with my Minio as an Azure Gateway and it works now.

**Comment by jmaitrehenry** [comment]
If you want to try, you can use my docker image: jmaitrehenry/minio

**Comment by EgoAleSum** [comment]
@jmaitrehenry I was typing right now asking how I can Docker-ize minio :) I'll test it right now!

**Comment by jmaitrehenry** [comment]
As simple as 
```
env GOOS=linux GOARCH=amd64 go build
docker build -t jmaitrehenry/minio -f Dockerfile.release .
```

But, you need to change the Dockerfile.release:
```diff
diff --git a/Dockerfile.release b/Dockerfile.release
index 4f064662..65713c8d 100644
--- a/Dockerfile.release
+++ b/Dockerfile.release
@@ -3,12 +3,12 @@ FROM alpine:3.6
 MAINTAINER Minio Inc <dev@minio.io>

 COPY dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
+COPY minio /usr/bin/minio

 RUN \
      apk add --no-cache ca-certificates && \
      apk add --no-cache --virtual .build-deps curl && \
      echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
-     curl https://dl.minio.io/server/minio/release/linux-amd64/minio > /usr/bin/minio && \
      chmod +x /usr/bin/minio  && \
      chmod +x /usr/bin/docker-entrypoint.sh && \
      chmod +x /usr/bin/healthcheck.sh
```

**Comment by EgoAleSum** [comment]
I've tested with jmaitrehenry/minio on Azure Web Apps, and it's working fine, both with small files (< 500 KB) and with a 15MB bigger file!
