### ISSUE TITLE
error when s3cmd mb

### ISSUE THREAD

**Issue by ce314007** [s3tools/s3cmd#910]
i have configure host base and host bucket in my rados like http://lollyrock.com/articles/s3cmd-with-radosgw/ and have configure withou error until s3cmd -c s3test.cfg ls. and next i want to tr make bucket but still error , i set port in 80 
![s3](https://user-images.githubusercontent.com/30142658/29109222-3f441098-7d1d-11e7-8707-b99a40d9c42d.PNG)

**Comment by fviard** [comment]
You can run the command with "-d" to have a debug output where you will see to what host address it tries to connect.

In your case, based on what you say, i suppose that you have a wrong configuration:
If you have enabled "https" on your radosgw instance, server should be listening to port 443 and not 80. If you want to have a server with https listening to another port like 80, then you should indicate it to s3cmd through the configuration file:
(fix host_base and host_bucket)
example:
host_base = radosgw.example.com
host_bucket = %(bucket)s.radosgw.example.com
becomes:
host_base = radosgw.example.com:80
host_bucket = %(bucket)s.radosgw.example.com:80

But in your case, i suppose that if your server is listening on port 80, it is just because you don't have the https support enabled on the server.
In that case, you should just indicate to s3cmd to not use https.
So set:
use_https = False
(Instead of True as in the link that you have provided).

I close the issue as it doesn't look to be an s3cmd command issue, but we can still continue the conversation here.
