### ISSUE TITLE
Ubuntu 17.10 shipping with outdated, broken s3cmd

### ISSUE THREAD

**Issue by Zenexer** [s3tools/s3cmd#931]
Ubuntu 17.10 shipped with a broken version of s3cmd.  The version of s3cmd currently in its repos, 2.0.0, has bug #898, which should be blocking.  There's an [open bug for this on Launchpad](https://bugs.launchpad.net/ubuntu/+source/s3cmd/+bug/1718948), but it hasn't received adequate attention.

**Comment by fviard** [comment]
Sadly the last release came too late to be on time for the 17.10.
That is not great but this is not a regression because it only affects python 3 support that was "experimental" and not python 2.7.
Also, you don't necessarily need to use "--configure" to have a working config file.
Anyway, lets see if we can have the package updated in ubuntu, that would be great as the 2.0.1 is quite good now.

**Comment by LocutusOfBorg** [comment]
I'm doing some testing right now. Hold on
(this issue can be closed, not an upstream issue)

**Comment by fviard** [comment]
Perfect
@LocutusOfBorg Thank you very much!
