### ISSUE TITLE
String "?acl" Appended to Filenames in Warnings

### ISSUE THREAD

**Issue by srguglielmo** [s3tools/s3cmd#934]
Hi,

I am using s3cmd 2.0.0 to sync a large directory (including sub directories) from a local machine to S3. I am seeing occasional warnings in which the filenames referenced have `?acl` appended, despite the fact that the actual filename on disk does not contain the string. Is this a bug or some internal s3cmd output?

Here are some examples:

> WARNING: Retrying failed request: /Full-2017-11-14/klein/files/files/images/news/2016/09/stock72dpi-4_0.jpg?acl (500 (InternalError): We encountered an internal error. Please try again.)

> WARNING: Retrying failed request: /Full-2017-11-14/smc_old/files/images/news/2017/01/imag0232_13.jpg?acl ('')

The files do seem to upload correctly during the retry and they do not have the "?acl" string appended.

Thanks,
Steve

**Comment by fviard** [comment]
Hi Steve,
There is nothing to worry about.
In s3 api, some special requests are done using such a syntax. ?acl, ?policy.
some_file?acl request is performed to get/set the acl info (access control list) of the file "some_file".

Some times, amazon s3 servers have very short transient issues, that's why we have a retry logic to wait a little bit and then retry the failed request.
Hopefully, that is enough for cases like yours.
