### ISSUE TITLE
S3 upload-only permisssions get forbidden on initiating a sync command

### ISSUE THREAD

**Issue by mtxd** [s3tools/s3cmd#948]
I have created upload-only rights for S3 user. put is working fine, however sync fails with 403.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:ListAllMyBuckets",
                "s3:ListObjects",
                "s3:PutObjectAcl"
            ],
            "Resource": "*"
        }
    ]
}
```

`/opt/s3cmd/s3cmd --acl-private --preserve --storage-class=STANDARD_IA --multipart-chunk-size-mb=256 sync /backup/vm-images/201801/* s3://s3-bucket-name/vm_images/201801/`

**Comment by fviard** [comment]
You can check by running the command with the '-v'  or '-d'  flag.
But it is probably because you will need other right to have the remote
copy working during the sync.

**Comment by mtxd** [comment]
Correct, but it's not clear what kind of access does it require?

INFO: Retrieving list of remote files for s3://s3-bucket/vm_images/201801/somefile.tar.gz ...
ERROR: S3 error: 403 (AccessDenied): Access Denied

**Comment by fviard** [comment]
Yes, you would need a few more rights.
Here is the reply I did on another issue that should also be good to work in your case:

>I think that the following one a stack overflow article is good:
> https://stackoverflow.com/questions/11603583/necessary-s3cmd-s3-permissions-for-put-sync
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1397834652000",
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Sid": "Stmt1397834745000",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads",
                "s3:GetBucketLocation",
                "s3:AbortMultipartUpload",
                "s3:GetObjectAcl",
                "s3:GetObjectVersion",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion",
                "s3:GetObject",
                "s3:PutObjectAcl",
                "s3:PutObject",
                "s3:GetObjectVersionAcl"
            ],
            "Resource": [
                "arn:aws:s3:::my_bucket",
                "arn:aws:s3:::my_bucket/*"
            ]
        }
    ]
}
```
You can probably remove the delete permissions if you use: --no-delete-removed.
Otherwise, you need to understand what kind of operations are done with a sync:
we look at your local files and look at what is on the cloud, and then upload/remote copy only what is necessary.

I'm not 100% sure, but I think that if you would like a configuration that would be more "upload-only", you can use the "s3cmd put" instead of "s3cmd sync", but in that case, it will just re-upload everything each time as it will not have a look on the cloud for what is already there.
