### ISSUE TITLE
cp/mv return value 1 for successful operations

### ISSUE THREAD

**Issue by dkechag** [s3tools/s3cmd#964]
My cp/mv operations seem to succeed, but return 1 (instead of 0), which makes it hard for the caller to determine whether they are successful. It happens both from bucket to bucket and within bucket cp/mv. Example extract from debug/verbose log:

[debug.log](https://github.com/s3tools/s3cmd/files/1915122/debug.log)

It seems weird in that it does 2 PUT attempts, the first successful the second not? Am I reading this right?

**Comment by fviard** [comment]
@dkechag When a copy is done, 2 steps are needed:
1) PUT file2.txt
The file "content" is copied to a new name.
2) PUT file2.txt?acl
The acl (access right policy) of the old file is "set" on the new file.

In what we can see in your log, it is this second step that fails.
So, you think that everything is good because the file looks to be "copied", but in fact the acl policy on the new file is probably wrong. (It is the default one, not the one of file1.txt).

This is probably due to missing rights of the s3 user you run s3cmd with.
You should check your policy.
I think that the following one a stack overflow article is good:
https://stackoverflow.com/questions/11603583/necessary-s3cmd-s3-permissions-for-put-sync?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Sid": "Stmt1397834652000",
>             "Effect": "Allow",
>             "Action": [
>                 "s3:ListAllMyBuckets"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::*"
>             ]
>         },
>         {
>             "Sid": "Stmt1397834745000",
>             "Effect": "Allow",
>             "Action": [
>                 "s3:ListBucket",
>                 "s3:ListBucketMultipartUploads",
>                 "s3:GetBucketLocation",
>                 "s3:AbortMultipartUpload",
>                 "s3:GetObjectAcl",
>                 "s3:GetObjectVersion",
>                 "s3:DeleteObject",
>                 "s3:DeleteObjectVersion",
>                 "s3:GetObject",
>                 "s3:PutObjectAcl",
>                 "s3:PutObject",
>                 "s3:GetObjectVersionAcl"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::my_bucket",
>                 "arn:aws:s3:::my_bucket/*"
>             ]
>         }
>     ]
> }

**Comment by dkechag** [comment]
Ah, user error. Apologies and thanks for the explanation.
