### ISSUE TITLE
Access SFTP / SSH directory as Source?

### ISSUE THREAD

**Issue by jamiejackson** [s3tools/s3cmd#969]
For several years, I've been happily using s3cmd from a script, which:

* FUSE-mounts a remote SSH directory
* Calls s3cmd and syncs from the mount point to S3.
* Unmounts the SSH directory

However, I'd like to migrate to lambda (or docker as a backup plan). The FUSE mount requirement is something I'd like to avoid (since it's a non-starter in lambda and a bit weird in docker). Is there any way to use say, paramiko, to access the remote directory and use that source, instead?

**Comment by jamiejackson** [comment]
@fviard, unfortunately, the remote SSH host is not mine, and I'm limited in what I can do there. I think it would be pushing their expectations to run sophisticated commands there (especially `cron`ed), and the machine can't reach the internet.

> Things that are possible with a lot of protocol/service is to tunnel a connection through ssh if it is the requirement.

Could you expand on that, to make sure I'm not missing something important?

**Comment by fviard** [comment]
What i was meaning is that if the secure connection was the issue, it is possible to have some software like s3cmd running on the "ssh host", and to create a ssh connection tunnel between the two machines and ask the s3cmd or else to send data through this tunnel instead of direct connexion.

Otherwise, if you use rsync over ssh to retrieve your data, rsync from your "cloud" machine will create a ssh tunnel and then do a normal remote rsync operation inside.

**Comment by jamiejackson** [comment]
Okay, thanks, @fviard. Given my constraints (and not wanting to maintain an intermediate mirror of the data between the SSH server), I think I'll abandon the lambda idea and try it with docker, or the failsafe, ec2.
