### ISSUE TITLE
Cron job to sync wp-content reporting in:trash ERROR: Parameter problem: Invalid source: '–delete-removed' is not an existing file or directory

### ISSUE THREAD

**Issue by bluehiveinteractive** [s3tools/s3cmd#978]
have cron job running to sync /wp-content using the following cron, 

/usr/bin/s3cmd sync -r -delete-removed –add-header “Cache-Control:max-age=31536000” /home/USERNAME/public_html/wp-content/ s3://www.MYDOMAIN.com/wp-content/

but getting the error reported

in:trash ERROR: Parameter problem: Invalid source: '–delete-removed' is not an existing file or directory

**Comment by fviard** [comment]
Are you sure of the "-" characters that you use in your command line?
In what you pasted, there is just a single "minus" before the option "delete-removed" instead of two.
And the one in front of "add-header" looks weird also. It should be "--"

**Comment by bluehiveinteractive** [comment]
I just updated the cron to use the double -- "minus" /usr/bin/s3cmd sync -r –-delete-removed –add-header "Cache-Control:max-age=31536000" /home/USERNAME/public_html/wp-content/ s3://www.MYDOMAIN.com/wp-content/ but it still reports the error of

ERROR: Parameter problem: Invalid source: '–-delete-removed' is not an existing file or directory

**Comment by bluehiveinteractive** [comment]
It is now working. I am not sure if there was an encoding conflict with the text I was copying or pasting or what, but it's working now. Thanks for your insight.

**Comment by fviard** [comment]
FYI, in the last error you reported:
> ERROR: Parameter problem: Invalid source: '–-delete-removed' is not an existing file or directory'
if you look closely, you can see that the first minus is an anormal one (a very long one), and the second one is normal.
That is why it failed.
I think your issue come from a copy paste error, because it already happened to me that copying commands from a service was resulting in the big "–" instead of the real "-".
But sadly I don't remember which service it was. (Maybe gdocs or office docs, slack, emails, ...)
